<?php

return [
    'theme' => [
        'canvas' => '#278d4e',
        'paper' => '#f4f0e5',
        'paperAlt' => '#f8f6ef',
        'paperTint' => '#e9e6d7',
        'paperInput' => '#fffdf6',
        'ink' => '#172331',
        'copy' => '#334247',
        'copyAlt' => '#344344',
        'muted' => '#53605b',
        'green' => '#176b49',
        'greenDark' => '#0b503b',
        'blue' => '#2052b5',
        'blueDark' => '#153f91',
        'yellow' => '#f0c33c',
        'onAccent' => '#ffffff',
        'rule' => '#c8c7c1',
        'adminBackground' => '#050506',
        'adminPanel' => '#15151c',
        'adminPanelBorder' => '#44444a',
        'adminInput' => '#0e0e12',
        'adminInputBorder' => '#505057',
        'adminText' => '#ffffff',
        'adminMuted' => '#dedee0',
        'adminRule' => '#393941',
        'adminAccent' => '#d8d9f3',
        'adminAccentMuted' => '#9498cc',
        'successBg' => '#e2eee3',
        'successText' => '#0b503b',
        'dangerBg' => '#f7e5d7',
        'dangerText' => '#8d2525',
        'danger' => '#991b1b',
        'dangerLight' => '#fecaca',
        'shadow' => '#043425',
    ],
    'social_links' => [
        'instagram' => '',
        'linkedin' => '',
        'github' => '',
    ],
];
